# Generated by Django 6.1 on 2026-08-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='named_voting',
            field=models.BooleanField(default=False),
        ),
    ]
