# Generated by Django 6.1 on 2026-08-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_poll_named_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='allow_voter_options',
            field=models.BooleanField(default=False),
        ),
    ]
